spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_microservice
    username: root
    password: Coder_1234
    #driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /transaction-microservice/api/v1